# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeHunter的博客(本地版)
email: CodeHunter2006@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这里包括一些技术经验总结、生活随想和其他...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://192.168.2.135:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  CodeHunter2006

# Build settings
markdown: kramdown

# Plugins
whitelist: []
gems:      ["jekyll-paginate"]

paginate: 5

# Serving
#port: 4001
#host: 0.0.0.0
